// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct ReputationOracleClientProgram;

impl sails_rs::client::Program for ReputationOracleClientProgram {}

pub trait ReputationOracleClient {
    type Env: sails_rs::client::GearEnv;
    fn reputation_oracle(
        &self,
    ) -> sails_rs::client::Service<reputation_oracle::ReputationOracleImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> ReputationOracleClient
    for sails_rs::client::Actor<ReputationOracleClientProgram, E>
{
    type Env = E;
    fn reputation_oracle(
        &self,
    ) -> sails_rs::client::Service<reputation_oracle::ReputationOracleImpl, Self::Env> {
        self.service(stringify!(ReputationOracle))
    }
}

pub trait ReputationOracleClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<ReputationOracleClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> ReputationOracleClientCtors
    for sails_rs::client::Deployment<ReputationOracleClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<ReputationOracleClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod reputation_oracle {
    use super::*;

    pub trait ReputationOracle {
        type Env: sails_rs::client::GearEnv;
        fn add_read_model_operator(
            &mut self,
            operator: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddReadModelOperator, Self::Env>;
        fn fund_reward_pool(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::FundRewardPool, Self::Env>;
        fn open_usage_prediction(
            &mut self,
            epoch_id: u32,
            subject: String,
            window_start_ms: u64,
            window_end_ms: u64,
            predicted_delta_calls: u32,
            evidence_hash: String,
        ) -> sails_rs::client::PendingCall<io::OpenUsagePrediction, Self::Env>;
        fn record_attestation(
            &mut self,
            subject: String,
            issuer: String,
            kind: String,
            weight: i32,
            evidence_hash: String,
        ) -> sails_rs::client::PendingCall<io::RecordAttestation, Self::Env>;
        fn remove_read_model_operator(
            &mut self,
            operator: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveReadModelOperator, Self::Env>;
        fn set_read_only(
            &mut self,
            read_only: bool,
        ) -> sails_rs::client::PendingCall<io::SetReadOnly, Self::Env>;
        fn settle_usage_prediction(
            &mut self,
            position_id: String,
            actual_delta_calls: u32,
            settlement_snapshot_hash: String,
        ) -> sails_rs::client::PendingCall<io::SettleUsagePrediction, Self::Env>;
        fn submit_integration_signal(
            &mut self,
            agent: String,
            subject: String,
            counterparty: String,
            evidence_hash: String,
            observed_value: u32,
            virtual_stake: u32,
        ) -> sails_rs::client::PendingCall<io::SubmitIntegrationSignal, Self::Env>;
        fn upsert_read_model(
            &mut self,
            subject: String,
            signals: ReputationSignals,
            evidence: Vec<String>,
        ) -> sails_rs::client::PendingCall<io::UpsertReadModel, Self::Env>;
        fn compare_agents(
            &self,
            subjects: Vec<String>,
            track: String,
            need: String,
        ) -> sails_rs::client::PendingCall<io::CompareAgents, Self::Env>;
        fn economic_leaderboard(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::EconomicLeaderboard, Self::Env>;
        fn economic_profile(
            &self,
            agent: String,
        ) -> sails_rs::client::PendingCall<io::EconomicProfile, Self::Env>;
        fn export_attestations_chunk(
            &self,
            cursor: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ExportAttestationsChunk, Self::Env>;
        fn export_migration_config(
            &self,
        ) -> sails_rs::client::PendingCall<io::ExportMigrationConfig, Self::Env>;
        fn export_operators(&self)
        -> sails_rs::client::PendingCall<io::ExportOperators, Self::Env>;
        fn export_read_models_chunk(
            &self,
            cursor: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ExportReadModelsChunk, Self::Env>;
        fn export_signal_receipts_chunk(
            &self,
            cursor: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ExportSignalReceiptsChunk, Self::Env>;
        fn export_stats(&self) -> sails_rs::client::PendingCall<io::ExportStats, Self::Env>;
        fn export_usage_predictions_chunk(
            &self,
            cursor: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ExportUsagePredictionsChunk, Self::Env>;
        fn get_attestations(
            &self,
            subject: String,
        ) -> sails_rs::client::PendingCall<io::GetAttestations, Self::Env>;
        fn oracle_status(&self) -> sails_rs::client::PendingCall<io::OracleStatus, Self::Env>;
        fn read_model_policy(
            &self,
        ) -> sails_rs::client::PendingCall<io::ReadModelPolicy, Self::Env>;
        fn recommend_agents(
            &self,
            track: String,
            need: String,
            limit: u32,
            min_confidence: u8,
            include_avoid: bool,
        ) -> sails_rs::client::PendingCall<io::RecommendAgents, Self::Env>;
        fn score_agent(
            &self,
            subject: String,
        ) -> sails_rs::client::PendingCall<io::ScoreAgent, Self::Env>;
        fn score_agent_v_2(
            &self,
            subject: String,
            signals: ReputationSignalsV2,
            evidence: Vec<String>,
        ) -> sails_rs::client::PendingCall<io::ScoreAgentV2, Self::Env>;
    }

    pub struct ReputationOracleImpl;

    impl<E: sails_rs::client::GearEnv> ReputationOracle
        for sails_rs::client::Service<ReputationOracleImpl, E>
    {
        type Env = E;
        fn add_read_model_operator(
            &mut self,
            operator: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddReadModelOperator, Self::Env> {
            self.pending_call((operator,))
        }
        fn fund_reward_pool(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::FundRewardPool, Self::Env> {
            self.pending_call(())
        }
        fn open_usage_prediction(
            &mut self,
            epoch_id: u32,
            subject: String,
            window_start_ms: u64,
            window_end_ms: u64,
            predicted_delta_calls: u32,
            evidence_hash: String,
        ) -> sails_rs::client::PendingCall<io::OpenUsagePrediction, Self::Env> {
            self.pending_call((
                epoch_id,
                subject,
                window_start_ms,
                window_end_ms,
                predicted_delta_calls,
                evidence_hash,
            ))
        }
        fn record_attestation(
            &mut self,
            subject: String,
            issuer: String,
            kind: String,
            weight: i32,
            evidence_hash: String,
        ) -> sails_rs::client::PendingCall<io::RecordAttestation, Self::Env> {
            self.pending_call((subject, issuer, kind, weight, evidence_hash))
        }
        fn remove_read_model_operator(
            &mut self,
            operator: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveReadModelOperator, Self::Env> {
            self.pending_call((operator,))
        }
        fn set_read_only(
            &mut self,
            read_only: bool,
        ) -> sails_rs::client::PendingCall<io::SetReadOnly, Self::Env> {
            self.pending_call((read_only,))
        }
        fn settle_usage_prediction(
            &mut self,
            position_id: String,
            actual_delta_calls: u32,
            settlement_snapshot_hash: String,
        ) -> sails_rs::client::PendingCall<io::SettleUsagePrediction, Self::Env> {
            self.pending_call((position_id, actual_delta_calls, settlement_snapshot_hash))
        }
        fn submit_integration_signal(
            &mut self,
            agent: String,
            subject: String,
            counterparty: String,
            evidence_hash: String,
            observed_value: u32,
            virtual_stake: u32,
        ) -> sails_rs::client::PendingCall<io::SubmitIntegrationSignal, Self::Env> {
            self.pending_call((
                agent,
                subject,
                counterparty,
                evidence_hash,
                observed_value,
                virtual_stake,
            ))
        }
        fn upsert_read_model(
            &mut self,
            subject: String,
            signals: ReputationSignals,
            evidence: Vec<String>,
        ) -> sails_rs::client::PendingCall<io::UpsertReadModel, Self::Env> {
            self.pending_call((subject, signals, evidence))
        }
        fn compare_agents(
            &self,
            subjects: Vec<String>,
            track: String,
            need: String,
        ) -> sails_rs::client::PendingCall<io::CompareAgents, Self::Env> {
            self.pending_call((subjects, track, need))
        }
        fn economic_leaderboard(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::EconomicLeaderboard, Self::Env> {
            self.pending_call((limit,))
        }
        fn economic_profile(
            &self,
            agent: String,
        ) -> sails_rs::client::PendingCall<io::EconomicProfile, Self::Env> {
            self.pending_call((agent,))
        }
        fn export_attestations_chunk(
            &self,
            cursor: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ExportAttestationsChunk, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn export_migration_config(
            &self,
        ) -> sails_rs::client::PendingCall<io::ExportMigrationConfig, Self::Env> {
            self.pending_call(())
        }
        fn export_operators(
            &self,
        ) -> sails_rs::client::PendingCall<io::ExportOperators, Self::Env> {
            self.pending_call(())
        }
        fn export_read_models_chunk(
            &self,
            cursor: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ExportReadModelsChunk, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn export_signal_receipts_chunk(
            &self,
            cursor: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ExportSignalReceiptsChunk, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn export_stats(&self) -> sails_rs::client::PendingCall<io::ExportStats, Self::Env> {
            self.pending_call(())
        }
        fn export_usage_predictions_chunk(
            &self,
            cursor: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ExportUsagePredictionsChunk, Self::Env> {
            self.pending_call((cursor, limit))
        }
        fn get_attestations(
            &self,
            subject: String,
        ) -> sails_rs::client::PendingCall<io::GetAttestations, Self::Env> {
            self.pending_call((subject,))
        }
        fn oracle_status(&self) -> sails_rs::client::PendingCall<io::OracleStatus, Self::Env> {
            self.pending_call(())
        }
        fn read_model_policy(
            &self,
        ) -> sails_rs::client::PendingCall<io::ReadModelPolicy, Self::Env> {
            self.pending_call(())
        }
        fn recommend_agents(
            &self,
            track: String,
            need: String,
            limit: u32,
            min_confidence: u8,
            include_avoid: bool,
        ) -> sails_rs::client::PendingCall<io::RecommendAgents, Self::Env> {
            self.pending_call((track, need, limit, min_confidence, include_avoid))
        }
        fn score_agent(
            &self,
            subject: String,
        ) -> sails_rs::client::PendingCall<io::ScoreAgent, Self::Env> {
            self.pending_call((subject,))
        }
        fn score_agent_v_2(
            &self,
            subject: String,
            signals: ReputationSignalsV2,
            evidence: Vec<String>,
        ) -> sails_rs::client::PendingCall<io::ScoreAgentV2, Self::Env> {
            self.pending_call((subject, signals, evidence))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddReadModelOperator (operator: ActorId) -> super::OperatorReceipt);
        sails_rs::io_struct_impl!(FundRewardPool () -> super::RewardPoolReceipt);
        sails_rs::io_struct_impl!(OpenUsagePrediction (epoch_id: u32, subject: String, window_start_ms: u64, window_end_ms: u64, predicted_delta_calls: u32, evidence_hash: String) -> super::UsagePredictionReceipt);
        sails_rs::io_struct_impl!(RecordAttestation (subject: String, issuer: String, kind: String, weight: i32, evidence_hash: String) -> super::AttestationReceipt);
        sails_rs::io_struct_impl!(RemoveReadModelOperator (operator: ActorId) -> super::OperatorReceipt);
        sails_rs::io_struct_impl!(SetReadOnly (read_only: bool) -> super::ReadOnlyReceipt);
        sails_rs::io_struct_impl!(SettleUsagePrediction (position_id: String, actual_delta_calls: u32, settlement_snapshot_hash: String) -> super::PredictionSettlement);
        sails_rs::io_struct_impl!(SubmitIntegrationSignal (agent: String, subject: String, counterparty: String, evidence_hash: String, observed_value: u32, virtual_stake: u32) -> super::SignalReceipt);
        sails_rs::io_struct_impl!(UpsertReadModel (subject: String, signals: super::ReputationSignals, evidence: Vec<String>) -> super::ReadModelReceipt);
        sails_rs::io_struct_impl!(CompareAgents (subjects: Vec<String>, track: String, need: String) -> super::AgentComparison);
        sails_rs::io_struct_impl!(EconomicLeaderboard (limit: u32) -> Vec<super::EconomicProfile>);
        sails_rs::io_struct_impl!(EconomicProfile (agent: String) -> super::EconomicProfile);
        sails_rs::io_struct_impl!(ExportAttestationsChunk (cursor: u32, limit: u32) -> super::AttestationExportChunk);
        sails_rs::io_struct_impl!(ExportMigrationConfig () -> super::MigrationConfig);
        sails_rs::io_struct_impl!(ExportOperators () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(ExportReadModelsChunk (cursor: u32, limit: u32) -> super::ReadModelExportChunk);
        sails_rs::io_struct_impl!(ExportSignalReceiptsChunk (cursor: u32, limit: u32) -> super::SignalReceiptExportChunk);
        sails_rs::io_struct_impl!(ExportStats () -> super::MigrationStats);
        sails_rs::io_struct_impl!(ExportUsagePredictionsChunk (cursor: u32, limit: u32) -> super::UsagePredictionExportChunk);
        sails_rs::io_struct_impl!(GetAttestations (subject: String) -> Vec<super::AttestationReceipt>);
        sails_rs::io_struct_impl!(OracleStatus () -> super::OracleStatus);
        sails_rs::io_struct_impl!(ReadModelPolicy () -> super::ReadModelPolicy);
        sails_rs::io_struct_impl!(RecommendAgents (track: String, need: String, limit: u32, min_confidence: u8, include_avoid: bool) -> Vec<super::AgentRecommendation>);
        sails_rs::io_struct_impl!(ScoreAgent (subject: String) -> super::ReputationReport);
        sails_rs::io_struct_impl!(ScoreAgentV2 (subject: String, signals: super::ReputationSignalsV2, evidence: Vec<String>) -> super::ReputationReportV2);
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct OperatorReceipt {
    pub operator: ActorId,
    pub added: bool,
    pub removed: bool,
    pub operator_count: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct RewardPoolReceipt {
    pub funder: ActorId,
    pub value_added: u128,
    pub reward_pool_balance: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct UsagePredictionReceipt {
    pub position_id: String,
    pub predictor: ActorId,
    pub epoch_id: u32,
    pub subject: String,
    pub window_start_ms: u64,
    pub window_end_ms: u64,
    pub opened_at_ms: u64,
    pub predicted_delta_calls: u32,
    pub stake: u128,
    pub effective_stake: u128,
    pub late_penalty_bps: u32,
    pub late_penalty_value: u128,
    pub reward_pool_balance: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AttestationReceipt {
    pub receipt_id: String,
    pub subject: String,
    pub issuer: String,
    pub kind: String,
    pub weight: i32,
    pub evidence_hash: String,
    pub issued_at: String,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ReadOnlyReceipt {
    pub owner: ActorId,
    pub previous_status: OracleStatus,
    pub status: OracleStatus,
    pub read_only: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum OracleStatus {
    Active,
    ReadOnly,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PredictionSettlement {
    pub position_id: String,
    pub subject: String,
    pub predicted_delta_calls: u32,
    pub actual_delta_calls: u32,
    pub settlement_snapshot_hash: String,
    pub error_bps: u32,
    pub status: PredictionStatus,
    pub stake: u128,
    pub effective_stake: u128,
    pub late_penalty_bps: u32,
    pub payout: u128,
    pub reward_pool_balance: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum PredictionStatus {
    Open,
    Won,
    Lost,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SignalReceipt {
    pub receipt_id: String,
    pub agent: String,
    pub subject: String,
    pub counterparty: String,
    pub evidence_hash: String,
    pub observed_value: u32,
    pub virtual_stake: u32,
    pub value_attached: u128,
    pub value_rewarded: u128,
    pub value_slashed: u128,
    pub quality_score: u8,
    pub points_delta: i32,
    pub profile_points: i32,
    pub reward_pool_balance: u128,
    pub verdict: String,
    pub reason: String,
    pub as_of: String,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ReputationSignals {
    pub incoming_unique_callers: u32,
    pub outgoing_meaningful_calls: u32,
    pub chat_board_updates: u32,
    pub has_identity_card: bool,
    pub has_verified_social_proof: bool,
    pub circular_call_signals: u32,
    pub missing_required_metadata: u32,
    pub positive_attestations: u32,
    pub negative_attestations: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ReadModelReceipt {
    pub subject: String,
    pub replaced: bool,
    pub evicted_subject: Option<String>,
    pub stored_subjects: u32,
    pub report: ReputationReport,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ReputationReport {
    pub subject: String,
    pub as_of: String,
    pub report_version: u32,
    pub scores: ReputationScores,
    pub signals: ReputationSignals,
    pub integration_decision: IntegrationDecision,
    pub evidence: Vec<String>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ReputationScores {
    pub trust_score: u8,
    pub activity_score: u8,
    pub integration_score: u8,
    pub identity_score: u8,
    pub spam_risk: u8,
    pub confidence: u8,
    pub verdict: String,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct IntegrationDecision {
    pub action: String,
    pub risk_level: String,
    pub max_attestation_weight: i32,
    pub next_steps: Vec<String>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AgentComparison {
    pub track: String,
    pub need: String,
    pub winner: ComparableAgent,
    pub candidates: Vec<ComparableAgent>,
    pub decision: ComparisonDecision,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ComparableAgent {
    pub input: String,
    pub subject: String,
    pub verdict: String,
    pub trust_score: u8,
    pub confidence: u8,
    pub spam_risk: u8,
    pub reason: String,
    pub report: ReputationReport,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ComparisonDecision {
    pub winner: String,
    pub runner_up: Option<String>,
    pub trust_margin: i32,
    pub spam_risk_advantage: i32,
    pub summary: String,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct EconomicProfile {
    pub agent: String,
    pub oracle_points: i32,
    pub total_value_staked: u128,
    pub total_value_rewarded: u128,
    pub total_value_slashed: u128,
    pub virtual_stake: u32,
    pub useful_signals: u32,
    pub spam_signals: u32,
    pub last_verdict: String,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AttestationExportChunk {
    pub cursor: u32,
    pub limit: u32,
    pub next_cursor: u32,
    pub done: bool,
    pub total: u32,
    pub items: Vec<AttestationReceipt>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MigrationConfig {
    pub owner: ActorId,
    pub status: OracleStatus,
    pub read_only: bool,
    pub bounds: MigrationBounds,
    pub operator_count: u32,
    pub read_model_count: u32,
    pub attestation_count: u32,
    pub as_of: String,
    pub report_version: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MigrationBounds {
    pub max_operators: u32,
    pub max_read_models: u32,
    pub max_attestations: u32,
    pub max_evidence_labels: u32,
    pub max_evidence_label_chars: u32,
    pub max_export_chunk: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ReadModelExportChunk {
    pub cursor: u32,
    pub limit: u32,
    pub next_cursor: u32,
    pub done: bool,
    pub total: u32,
    pub items: Vec<AgentReadModel>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AgentReadModel {
    pub subject: String,
    pub signals: ReputationSignals,
    pub evidence: Vec<String>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SignalReceiptExportChunk {
    pub cursor: u32,
    pub limit: u32,
    pub next_cursor: u32,
    pub done: bool,
    pub total: u32,
    pub items: Vec<SignalReceipt>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MigrationStats {
    pub operator_count: u32,
    pub read_model_count: u32,
    pub attestation_count: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct UsagePredictionExportChunk {
    pub cursor: u32,
    pub limit: u32,
    pub next_cursor: u32,
    pub done: bool,
    pub total: u32,
    pub items: Vec<UsagePrediction>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct UsagePrediction {
    pub position_id: String,
    pub predictor: ActorId,
    pub epoch_id: u32,
    pub subject: String,
    pub window_start_ms: u64,
    pub window_end_ms: u64,
    pub opened_at_ms: u64,
    pub predicted_delta_calls: u32,
    pub evidence_hash: String,
    pub stake: u128,
    pub effective_stake: u128,
    pub late_penalty_bps: u32,
    pub late_penalty_value: u128,
    pub opened_at: String,
    pub status: PredictionStatus,
    pub actual_delta_calls: Option<u32>,
    pub settlement_snapshot_hash: Option<String>,
    pub error_bps: Option<u32>,
    pub payout: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ReadModelPolicy {
    pub owner: ActorId,
    pub caller: ActorId,
    pub caller_can_upsert: bool,
    pub operator_count: u32,
    pub max_operators: u32,
    pub max_read_models: u32,
    pub max_evidence_labels: u32,
    pub max_evidence_label_chars: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AgentRecommendation {
    pub subject: String,
    pub track: String,
    pub need: String,
    pub verdict: String,
    pub trust_score: u8,
    pub confidence: u8,
    pub spam_risk: u8,
    pub reason: String,
    pub explanation: RecommendationExplanation,
    pub report: ReputationReport,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct RecommendationExplanation {
    pub summary: String,
    pub positive_signals: Vec<String>,
    pub negative_signals: Vec<String>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ReputationSignalsV2 {
    pub inbound_unique_participants: u32,
    pub inbound_call_count: u32,
    pub outbound_unique_participants: u32,
    pub outbound_call_count: u32,
    pub valid_participant_inbound_count: u32,
    pub valid_participant_outbound_count: u32,
    pub non_participant_call_count: u32,
    pub self_loop_call_count: u32,
    pub same_owner_call_count: u32,
    pub mention_count: u32,
    pub messages_sent: u32,
    pub posts_active: u32,
    pub has_clear_board_description: bool,
    pub has_identity_card: bool,
    pub has_actual_github_repo: bool,
    pub has_skills_url: bool,
    pub has_idl_url: bool,
    pub has_frontend_url: bool,
    pub handle_claimed: bool,
    pub application_status: ApplicationStatusV2,
    pub participant_status: ParticipantStatusV2,
    pub call_graph_density_bps: u32,
    pub low_diversity_volume_count: u32,
    pub reciprocal_farming_signals: u32,
    pub positive_third_party_attestations: u32,
    pub negative_third_party_attestations: u32,
    pub metrics_updated_at: u64,
    pub identity_updated_at: u64,
    pub registered_at: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ApplicationStatusV2 {
    Unknown,
    Draft,
    Submitted,
    Approved,
    Rejected,
    Suspended,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ParticipantStatusV2 {
    Unknown,
    ParticipantLike,
    VerifiedParticipant,
    NonParticipant,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ReputationReportV2 {
    pub subject: String,
    pub as_of: String,
    pub report_version: u32,
    pub signals: ReputationSignalsV2,
    pub scores: ReputationScoresV2,
    pub evidence: Vec<String>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ReputationScoresV2 {
    pub ecosystem_value_score: u8,
    pub real_integration_score: u8,
    pub counterparty_diversity_score: u8,
    pub identity_provenance_score: u8,
    pub demo_readiness_score: u8,
    pub safety_score: u8,
    pub spam_risk: u8,
    pub confidence_score: u8,
    pub overall_score: u8,
    pub verdict: String,
}
